### ISSUE TITLE
Response.url will be "hardened"

### ISSUE THREAD

**Issue by annevk** [WebAssembly/content-security-policy#4]
I suspect this comes from some kind of misunderstanding, but this seems incorrect. A `Response` already carries around a protection layer to prevent cross-origin leakage. Nothing more should be needed.

**Comment by titzer** [comment]
How does this "protection layer work"? For example, is it possible for an application to issue a cross-origin fetch that be allowed for one type of resource, but would be disallowed by the CSP policy for scripts? Since WASM streaming operations simply work on Response objects, it seems like there is no way to know whether CSP should be applied at the time of the fetch.

**Comment by annevk** [comment]
That's something else and indeed still needed therefore, but you should be able to obtain that information from a `Response` without "hardening" I think, though maybe synthetic responses make this hard.

**Comment by fgmccabe** [comment]
Discussion is moot at this point.
